# NumPy Exercises

#### Import NumPy as np

In [122]:
import numpy as np

#### Crear una matriz de 10 ceros

In [39]:
# CODE HERE
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### Crear una matriz con 10 unos

In [40]:
# CODE HERE
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

#### Create an array of 10 fives

In [42]:
# CODE HERE
np.ones(10)*5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [44]:
# CODE HERE
np.arange(10,49)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48])

#### Create an array of all the even integers from 10 to 50

In [46]:
# CODE HERE
np.arange(10, 48, 2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46])

#### Create a 3x3 matrix with values ranging from 0 to 8

##### Forma 1

In [48]:
matrix1 = [[0, 1 ,2], [3, 4, 5], [6, 7, 8]]
np.array(matrix1)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [49]:
matrix2 = np.arange(0,9).reshape(3 ,3)
matrix2

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

##### Forma 2

In [50]:
#podes partir del range del vector
#hacer una de unos
matrix_ones = np.ones(9).reshape(3,3)
matrix_ones

In [53]:
# multiplicarlas

#### Create a 3x3 identity matrix

In [ ]:
# CODE HERE
np.eye(3)

#### Use NumPy to generate a random number between 0 and 1

In [74]:
# CODE HERE
np.random.rand(1,1)

array([[0.81071932]])

#### Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution

In [75]:
# CODE HERE
np.random.randn(5,5)

array([[-2.11469653, -0.06105767,  0.49631926, -1.65215569,  0.04417573],
       [-0.59640382, -0.24715137, -0.93974838, -1.01232936,  1.372604  ],
       [-0.04475067, -0.98939248,  1.29885855,  2.57974102, -0.22043469],
       [ 0.78198887,  0.70497654, -0.36031967, -1.31685528, -0.21948343],
       [ 0.49144271,  0.89855561,  1.50681883,  1.17615567, -2.09511749]])

#### Create the following matrix:

In [78]:
'''array([[ 0.01,  0.02,  0.03,  0.04,  0.05,  0.06,  0.07,  0.08,  0.09,  0.1 ],
       [ 0.11,  0.12,  0.13,  0.14,  0.15,  0.16,  0.17,  0.18,  0.19,  0.2 ],
       [ 0.21,  0.22,  0.23,  0.24,  0.25,  0.26,  0.27,  0.28,  0.29,  0.3 ],
       [ 0.31,  0.32,  0.33,  0.34,  0.35,  0.36,  0.37,  0.38,  0.39,  0.4 ],
       [ 0.41,  0.42,  0.43,  0.44,  0.45,  0.46,  0.47,  0.48,  0.49,  0.5 ],
       [ 0.51,  0.52,  0.53,  0.54,  0.55,  0.56,  0.57,  0.58,  0.59,  0.6 ],
       [ 0.61,  0.62,  0.63,  0.64,  0.65,  0.66,  0.67,  0.68,  0.69,  0.7 ],
       [ 0.71,  0.72,  0.73,  0.74,  0.75,  0.76,  0.77,  0.78,  0.79,  0.8 ],
       [ 0.81,  0.82,  0.83,  0.84,  0.85,  0.86,  0.87,  0.88,  0.89,  0.9 ],
       [ 0.91,  0.92,  0.93,  0.94,  0.95,  0.96,  0.97,  0.98,  0.99,  1.  ]])'''

'array([[ 0.01,  0.02,  0.03,  0.04,  0.05,  0.06,  0.07,  0.08,  0.09,  0.1 ],\n       [ 0.11,  0.12,  0.13,  0.14,  0.15,  0.16,  0.17,  0.18,  0.19,  0.2 ],\n       [ 0.21,  0.22,  0.23,  0.24,  0.25,  0.26,  0.27,  0.28,  0.29,  0.3 ],\n       [ 0.31,  0.32,  0.33,  0.34,  0.35,  0.36,  0.37,  0.38,  0.39,  0.4 ],\n       [ 0.41,  0.42,  0.43,  0.44,  0.45,  0.46,  0.47,  0.48,  0.49,  0.5 ],\n       [ 0.51,  0.52,  0.53,  0.54,  0.55,  0.56,  0.57,  0.58,  0.59,  0.6 ],\n       [ 0.61,  0.62,  0.63,  0.64,  0.65,  0.66,  0.67,  0.68,  0.69,  0.7 ],\n       [ 0.71,  0.72,  0.73,  0.74,  0.75,  0.76,  0.77,  0.78,  0.79,  0.8 ],\n       [ 0.81,  0.82,  0.83,  0.84,  0.85,  0.86,  0.87,  0.88,  0.89,  0.9 ],\n       [ 0.91,  0.92,  0.93,  0.94,  0.95,  0.96,  0.97,  0.98,  0.99,  1.  ]])'

In [93]:
# CODE HERE
np.arange(0.01,1.01,0.01)

array([0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 , 0.11,
       0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 , 0.21, 0.22,
       0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 , 0.31, 0.32, 0.33,
       0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 , 0.41, 0.42, 0.43, 0.44,
       0.45, 0.46, 0.47, 0.48, 0.49, 0.5 , 0.51, 0.52, 0.53, 0.54, 0.55,
       0.56, 0.57, 0.58, 0.59, 0.6 , 0.61, 0.62, 0.63, 0.64, 0.65, 0.66,
       0.67, 0.68, 0.69, 0.7 , 0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77,
       0.78, 0.79, 0.8 , 0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88,
       0.89, 0.9 , 0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99,
       1.  ])

#### Create an array of 20 linearly spaced points between 0 and 1:

In [88]:
# CODE HERE
np.linspace(0.,1., 20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

## Numpy Indexing and Selection

Ahora se le darán algunas matrices y se le pedirá que replique los resultados de la matriz resultante:

In [81]:
# HERE IS THE GIVEN MATRIX CALLED MAT
# USE IT FOR THE FOLLOWING TASKS
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

#### array([[12, 13, 14, 15],
####        [17, 18, 19, 20],
####       [22, 23, 24, 25]])

In [105]:
#[fila:columna , fila:columna]
#Recordar que el ultimo valor no lo toma y que empieza en 0
# CODE HERE
mat[2:5,1:5]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

#### 20

In [97]:
# [fila, columna]
# CODE HERE
mat[3,4]

20

#### array([[ 2],
####        [ 7],
####        [12]])

In [110]:
# [fila_inicial : fila_final , columna]
# CODE HERE
mat[0:3, 1]

array([ 2,  7, 12])

#### array([21, 22, 23, 24, 25])

In [109]:
# CODE HERE
mat[4:]

array([[21, 22, 23, 24, 25]])

#### array([[16, 17, 18, 19, 20],
#### [21, 22, 23, 24, 25]])

In [108]:
# [fila inicial : fila final]
# CODE HERE
mat[3:5]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

### Now do the following

#### Get the sum of all the values in mat
325

In [111]:
# CODE HERE
np.sum(mat)

325

#### Get the standard deviation of the values in mat
7.2111025509279782

In [112]:
# CODE HERE
np.std(mat)

7.211102550927978

#### Get the sum of all the columns in mat
array([55, 60, 65, 70, 75])

In [120]:
# axis = 0 para sumar por columna
# CODE HERE
mat.sum(axis=0)

array([55, 60, 65, 70, 75])

## Bonus Question

Trabajamos mucho con datos aleatorios con numpy, pero ¿hay alguna manera de asegurarnos de que siempre obtengamos los mismos números aleatorios? [Click Here for a Hint](https://www.google.com/search?q=numpy+random+seed&rlz=1C1CHBF_enUS747US747&oq=numpy+random+seed&aqs=chrome..69i57j69i60j0l4.2087j0j7&sourceid=chrome&ie=UTF-8)

In [127]:
np.random.seed(1)